theme = "gruvbox"

[editor]
mouse = false
shell = ["fish", "-c"]
auto-format = true
bufferline = "multiple"
soft-wrap.enable = true
popup-border = "all"

[editor.statusline]
center = ["version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
# git-ignore = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1 


