[language-server.zls]
command = "zls"

[language-server.elixir]
command = "elixir-ls"

[language-server.tailwind-heex]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.gleam-lsp]
command = "gleam"
args = ["lsp"]

[[language]]
name = "gleam"
auto-format = true
language-servers = ["gleam-lsp"]
file-types = ["gleam"]

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "elixir"
auto-format = true
language-servers = ["tailwind-heex", "elixir"]
language-id = "phoenix-heex"

[[language]]
name = "heex"
language-id = "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls"]
auto-format = true

[[language]]
name = "zig"
language-servers = [ "zls" ]


# [[language]]
# name = "markdown"
# scope = "source.md"
# injection-regex = "md|markdown"
# file-types = ["md", "markdown"]
# roots = [".zk"]
# language-server = { command = "zk", args=["lsp"] }

[[grammar]]
name = "markdown"
source = { git = "https://github.com/MDeiml/tree-sitter-markdown", rev = "7e7aa9a25ca9729db9fe22912f8f47bdb403a979", subpath = "tree-sitter-markdown" }

